### STAGE 1: base image
ARG LOCALARCH
ARG BASE_IMAGE_REGISTRY=cgr.dev
FROM --platform=linux/$LOCALARCH $BASE_IMAGE_REGISTRY/chainguard/go:latest AS builder

### STAGE 2: build the manager binary
ARG TARGETPLATFORM
ARG TARGETARCH
ARG LOCALARCH

ENV GO111MODULE=on
ENV GOTOOLCHAIN=local
ENV GOPRIVATE='bitbucket.corp.amdocs.com/*'
ENV GOPROXY="http://docker-registry-proxy.corp.amdocs.com:8081/repository/goproxy"
ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY cmd cmd
COPY pkg pkg

RUN --mount=type=cache,target=/root/go/pkg/mod,rw         \
    --mount=type=cache,target=/root/.cache/go-build,rw    \
     CGO_ENABLED=0 GOARCH=${TARGETARCH} go mod tidy -v || \
     CGO_ENABLED=0 GOARCH=${TARGETARCH} go mod tidy -v

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
ARG LDFLAGS
RUN --mount=type=cache,target=/root/go/pkg/mod,rw             \
    --mount=type=cache,target=/root/.cache/go-build,rw        \
    echo "Building on $BUILDPLATFORM -> linux/$TARGETARCH" && \
    CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -ldflags "$LDFLAGS" -o kagent-go-adk cmd/main.go

# add CA certificates before installing other packages
ADD FullAmdocsCA.crt /etc/ssl/certs/FullAmdocsCA.crt
RUN cat /etc/ssl/certs/FullAmdocsCA.crt >> /etc/ssl/certs/ca-certificates.crt

### STAGE 2: final image
# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
ARG BASE_IMAGE_REGISTRY
FROM $BASE_IMAGE_REGISTRY/distroless/static:nonroot
ARG TARGETPLATFORM
ARG TARGETARCH
ARG VERSION

WORKDIR /
COPY --from=builder /workspace/kagent-go-adk /kagent-go-adk
COPY --from=builder /etc/ssl/certs /etc/ssl/certs

USER 65532:65532
ARG VERSION

LABEL org.opencontainers.image.source=https://github.com/kagent-dev/kagent
LABEL org.opencontainers.image.description="Go-based Agent Development Kit (ADK) for Kagent"
LABEL org.opencontainers.image.authors="Kagent Creators 🤖"
LABEL org.opencontainers.image.version="$VERSION"

EXPOSE 8080

ENTRYPOINT ["/kagent-go-adk"]
CMD ["--host", "0.0.0.0", "--port", "8080"]
